---
devices:
  samplerate: 48000
  chunksize: 1024
  target_level: 1024
  adjust_period: 3
  enable_resampling: true
  resampler_type: FastAsync
  capture_samplerate: 44100
  capture:
    type: Alsa
    channels: 2
    device: "hw:Loopback,0,0"
    format: S16LE
  playback:
    type: Alsa
    channels: 2
    device: "hw:Generic_1"
    format: S32LE

filters:
  lowpass_fir:
    type: Conv
    parameters:
      type: Raw 
      filename: filter.txt

mixers:
  mono:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false
      - dest: 1
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false

pipeline:
  - type: Mixer
    name: mono
  - type: Filter
    channel: 0
    names:
      - lowpass_fir
  - type: Filter
    channel: 1
    names:
      - lowpass_fir
   

