---
devices:
  samplerate: 96000
  chunksize: 1024
  silence_threshold: -61
  silence_timeout: 3.0
  enable_resampling: true
  resampler_type: AccurateAsync
  capture_samplerate: 44100
  capture:
    type: Pulse
    channels: 2
    device: "MySink.monitor"
    format: S16LE
  playback:
    type: Pulse
    channels: 2
    device: "alsa_output.pci-0000_03_00.6.analog-stereo"
    format: S32LE


   

