---
devices:
  samplerate: 44100
  chunksize: 1024
  capture:
    type: Alsa
    channels: 2
    device: "hw:Loopback,0,0"
    format: S16LE
  playback:
    type: Alsa
    channels: 4
    device: "hw:Generic_1"
    format: S32LE

filters:
  lowpass:
    type: Biquad
    parameters:
      type: Lowpass
      q: 0.5
      freq: 1000
  highpass:
    type: Biquad
    parameters:
      type: Highpass
      q: 0.5
      freq: 1000


mixers:
  to_sumdiff:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
            inverted: false
          - channel: 1
            gain: 0
            inverted: false
      - dest: 1
        sources:
          - channel: 0
            gain: 0
            inverted: false
          - channel: 1
            gain: 0
            inverted: true
  to_leftright:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -6.0206
            inverted: false
          - channel: 1
            gain: -6.0206
            inverted: false
      - dest: 1
        sources:
          - channel: 0
            gain: -6.0206
            inverted: false
          - channel: 1
            gain: -6.0206
            inverted: true

pipeline:
  - type: Mixer
    name: to_sumdiff
  - type: Filter
    channel: 0
    names:
      - lowpass
  - type: Filter
    channel: 1
    names:
      - highpass
  - type: Mixer
    name: to_leftright
   

