[package]
name = "camilladsp"
version = "0.0.6"
authors = ["Henrik Enquist <henrik.enquist@gmail.com>"]

[features]
default = ["alsa-backend", "pulse-backend"]
alsa-backend = ["alsa"]
pulse-backend = ["libpulse-simple-binding", "libpulse-binding"]
32bit = []

[dependencies]
alsa = { version = "0.4", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
rustfft = "3.0.0"
num-traits = "0.2"
signal-hook = "0.1.13"
libpulse-binding = { version = "2.0", optional = true }
libpulse-simple-binding = { version = "2.0", optional = true }
