[package]
name = "camilladsp"
version = "1.0.0-alpha4"
authors = ["Henrik Enquist <henrik.enquist@gmail.com>"]
description = "A flexible tool for processing audio"

[features]
default = ["websocket"]
pulse-backend = ["libpulse-simple-binding", "libpulse-binding"]
cpal-backend = ["cpal"]
jack-backend = ["cpal-backend", "cpal/jack"]
32bit = []
websocket = ["tungstenite"]
secure-websocket = ["websocket", "native-tls", "tungstenite/native-tls"]
FFTW = ["fftw"]
neon = ["rubato/neon"]
debug = []

[lib]
name = "camillalib"
path = "src/lib.rs"

[[bin]]
name = "camilladsp"
path = "src/bin.rs"


[target.'cfg(target_os="linux")'.dependencies]
alsa = "0.5.0"
nix = "0.20"

[target.'cfg(target_os="macos")'.dependencies]
#coreaudio-rs = { path = "../coreaudio-rs" }
coreaudio-rs = { git = "https://github.com/HEnquist/coreaudio-rs", tag="v0.11.1-rc1" }
crossbeam-channel = "0.5"

[target.'cfg(target_os="windows")'.dependencies]
#wasapi = { path = "../../rust/wasapi" }
#wasapi = { git = "https://github.com/HEnquist/wasapi-rs" }
wasapi = "0.9.0"
crossbeam-channel = "0.5"
#winapi = { version = "0.3", features = ["avrt"] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
serde_with = "1.11"
realfft = "2.0.1"
fftw = { version = "0.7.0", optional = true }
num-complex = "0.4"
num-integer = "0.1.44"
num-traits = "0.2"
signal-hook = "0.3.8"
rand = "0.8.3"
rand_distr = "0.4.0"
clap = "2.33.0"
lazy_static = "1.4.0"
log = "0.4.14"
flexi_logger = { version = "0.19.6", features = ["async", "colors"] }
time = {version= "0.3", features = ["local-offset", "formatting", "parsing"]}
tungstenite = { version = "0.16.0", optional = true, default-features = false }
native-tls = { version = "0.2.7", optional = true }
libpulse-binding = { version = "2.0", optional = true }
libpulse-simple-binding = { version = "2.0", optional = true }
rubato = "0.10.0"
#rubato = { git = "https://github.com/HEnquist/rubato", branch = "objectsafe" }
cpal = { version = "0.13.3", optional = true }
#rawsample = { path = "../../rust/rawsample" }
#rawsample = { git = "https://github.com/HEnquist/rawsample", branch = "main" }
rawsample = "0.1.1"

[build-dependencies]
version_check = "0.9"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "filters"
harness = false
