[package]
name = "camilladsp"
version = "0.0.1"
authors = ["Henrik Enquist <henrik.enquist@gmail.com>"]

[dependencies]
alsa = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
rustfft = "3.0.0"
num-traits = "0.2"
libpulse-binding = "2.0"
libpulse-simple-binding = "2.0"
