[package]
name = "camilladsp"
version = "0.3.1"
authors = ["Henrik Enquist <henrik.enquist@gmail.com>"]
description = "A flexible tool for processing audio"

[features]
default = ["alsa-backend", "pulse-backend", "socketserver"]
alsa-backend = ["alsa"]
pulse-backend = ["libpulse-simple-binding", "libpulse-binding"]
cpal-backend = ["cpal"]
32bit = []
socketserver = ["ws"]
FFTW = ["fftw"]

[lib]
name = "camillalib"
path = "src/lib.rs"

[[bin]]
name = "camilladsp"
path = "src/bin.rs"


[target.'cfg(target_os="linux")'.dependencies]
alsa = { version = "0.4", optional = true }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_with = "1.4.0"
realfft = "0.2.0"
fftw = { version = "0.6.2", optional = true }
num = "0.2"
signal-hook = "0.1.13"
rand = "0.7.3"
rand_distr = "0.2.2"
clap = "2.33.0"
log = "0.4.8"
env_logger = "0.7.1"
ws = { version = "0.9.1", optional = true }
libpulse-binding = { version = "2.0", optional = true }
libpulse-simple-binding = { version = "2.0", optional = true }
rubato = "0.4.3"
cpal = { version = "0.11.0", optional = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "filters"
harness = false
