[package]
name = "loop-example"
version = "0.0.1"
authors = ["Henrik Enquist <henrik.enquist@gmail.com>"]

[dependencies]
alsa = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

